In [2]:
import tensorflow as tf
import numpy as np

import os
os.environ["CUDA_VISIBLE_DEVICES"] = "-1"

In [4]:
x = tf.convert_to_tensor(np.random.rand(3, 2, 3))
x

<tf.Tensor: shape=(3, 2, 3), dtype=float64, numpy=
array([[[0.9827047 , 0.24575817, 0.5504432 ],
        [0.60083602, 0.39220152, 0.78816476]],

       [[0.65162018, 0.38473162, 0.47941295],
        [0.15802501, 0.56012943, 0.11809563]],

       [[0.07189691, 0.78278671, 0.43211583],
        [0.94734434, 0.62965043, 0.74092906]]])>

In [38]:
def _rotation_z(theta):
    r1 = tf.cos(theta[:,2:3])
    r2 = tf.sin(theta[:,2:3])
    zero = tf.zeros_like(r1)
    one = tf.ones_like(r1)
    first = tf.reshape(tf.concat([r1,-r2,zero,zero],axis=1),(-1,1,4))
    second = tf.reshape(tf.concat([r2,r1,zero,zero],axis=1),(-1,1,4))
    third = tf.reshape(tf.concat([zero,zero,one,zero],axis=1),(-1,1,4))
    fourth = tf.reshape(tf.concat([zero,zero,zero,one],axis=1),(-1,1,4))
    rotation_z = tf.concat([first,second,third,fourth],axis=1)
    rotation_z = tf.reshape(rotation_z,[-1,4,4])
    return rotation_z

_rotation_z(x[:0:1])

tf.Tensor(
[[[0.85229278]
  [0.7051478 ]]

 [[0.88726586]
  [0.99303481]]

 [[0.90808169]
  [0.73784178]]], shape=(3, 2, 1), dtype=float64)
tf.Tensor(
[[[ 0.85229278 -0.52306502  0.          0.        ]
  [ 0.7051478  -0.70906035  0.          0.        ]]

 [[ 0.88726586 -0.46125838  0.          0.        ]
  [ 0.99303481 -0.11782132  0.          0.        ]]

 [[ 0.90808169 -0.41879308  0.          0.        ]
  [ 0.73784178 -0.67497371  0.          0.        ]]], shape=(3, 2, 4), dtype=float64)


<tf.Tensor: shape=(6, 4, 4), dtype=float64, numpy=
array([[[ 0.85229278,  0.7051478 , -0.52306502, -0.70906035],
        [ 0.52306502,  0.70906035,  0.85229278,  0.7051478 ],
        [ 0.        ,  0.        ,  0.        ,  0.        ],
        [ 0.        ,  0.        ,  0.        ,  0.        ]],

       [[ 0.        ,  0.        ,  0.        ,  0.        ],
        [ 0.        ,  0.        ,  0.        ,  0.        ],
        [ 1.        ,  1.        ,  0.        ,  0.        ],
        [ 0.        ,  0.        ,  1.        ,  1.        ]],

       [[ 0.88726586,  0.99303481, -0.46125838, -0.11782132],
        [ 0.46125838,  0.11782132,  0.88726586,  0.99303481],
        [ 0.        ,  0.        ,  0.        ,  0.        ],
        [ 0.        ,  0.        ,  0.        ,  0.        ]],

       [[ 0.        ,  0.        ,  0.        ,  0.        ],
        [ 0.        ,  0.        ,  0.        ,  0.        ],
        [ 1.        ,  1.        ,  0.        ,  0.        ],
        [ 0. 